/*
 * foo_dsd_trellis - Multi-bit NTF coefficient tables
 * Auto-generated by tools/ntf_gen_multibit.py using pydelsig
 *
 * CRFB form: a[] = feedforward, g[] = resonator
 * Higher H_inf = more aggressive noise shaping (needs more quantizer levels)
 */

#ifndef NTF_MULTIBIT_H
#define NTF_MULTIBIT_H

#include "ntf.h"

/* mb_std: order=6, H_inf=1.5
 * Standard NTF (same as 1-bit, baseline multibit) */
static const ntf_filter_t ntf_mb_std_dsd64 = {
    .a = {0.0000559905, 0.0010532838, 0.0100372674, 0.0567247036, 0.2508093201, 0.5562851812},
    .g = {0.0001371989, 0.0010533685, 0.0020947555},
    .order = 6,
    .freq = 2822400u,
    .name = "mb_std-dsd64"
};
static const ntf_filter_t ntf_mb_std_dsd128 = {
    .a = {0.0000565672, 0.0010518073, 0.0102058718, 0.0569938471, 0.2525980326, 0.5557380649},
    .g = {0.0000343000, 0.0002633595, 0.0005237575},
    .order = 6,
    .freq = 5644800u,
    .name = "mb_std-dsd128"
};
static const ntf_filter_t ntf_mb_std_dsd256 = {
    .a = {0.0000567109, 0.0010514390, 0.0102480982, 0.0570610734, 0.2530454033, 0.5556011895},
    .g = {0.0000085750, 0.0000658410, 0.0001309436},
    .order = 6,
    .freq = 11289600u,
    .name = "mb_std-dsd256"
};
static const ntf_filter_t ntf_mb_std_dsd512 = {
    .a = {0.0000567468, 0.0010513470, 0.0102586596, 0.0570778762, 0.2531572580, 0.5555669646},
    .g = {0.0000021438, 0.0000164603, 0.0000327362},
    .order = 6,
    .freq = 22579200u,
    .name = "mb_std-dsd512"
};

/* mb_mod: order=6, H_inf=2.5
 * Moderate aggressive (stable with 4+ levels) */
static const ntf_filter_t ntf_mb_mod_dsd64 = {
    .a = {0.0044564792, 0.0375659037, 0.1756145051, 0.4163828755, 0.9654035261, 0.8402626700},
    .g = {0.0001371989, 0.0010533685, 0.0020947555},
    .order = 6,
    .freq = 2822400u,
    .name = "mb_mod-dsd64"
};
static const ntf_filter_t ntf_mb_mod_dsd128 = {
    .a = {0.0044595100, 0.0375052658, 0.1760912138, 0.4165132044, 0.9668830984, 0.8400657081},
    .g = {0.0000343000, 0.0002633595, 0.0005237575},
    .order = 6,
    .freq = 5644800u,
    .name = "mb_mod-dsd128"
};
static const ntf_filter_t ntf_mb_mod_dsd256 = {
    .a = {0.0044602649, 0.0374901224, 0.1762104459, 0.4165458150, 0.9672531156, 0.8400164329},
    .g = {0.0000085750, 0.0000658410, 0.0001309436},
    .order = 6,
    .freq = 11289600u,
    .name = "mb_mod-dsd256"
};
static const ntf_filter_t ntf_mb_mod_dsd512 = {
    .a = {0.0044604534, 0.0374863376, 0.1762402574, 0.4165539694, 0.9673456277, 0.8400041119},
    .g = {0.0000021438, 0.0000164603, 0.0000327362},
    .order = 6,
    .freq = 22579200u,
    .name = "mb_mod-dsd512"
};

/* mb_agg: order=8, H_inf=3.0
 * Aggressive order-8 (stable with 4+ levels) */
static const ntf_filter_t ntf_mb_agg_dsd64 = {
    .a = {0.0003719914, 0.0045793174, 0.0301283906, 0.1108971780, 0.3692902444, 0.6366499569, 1.2821083521, 0.8891385064},
    .g = {0.0000810795, 0.0006654515, 0.0015291072, 0.0022215911},
    .order = 8,
    .freq = 2822400u,
    .name = "mb_agg-dsd64"
};
static const ntf_filter_t ntf_mb_agg_dsd128 = {
    .a = {0.0003718756, 0.0045653445, 0.0302192580, 0.1109131502, 0.3705672737, 0.6371355821, 1.2840360642, 0.8889513413},
    .g = {0.0000202700, 0.0001663698, 0.0003823133, 0.0005554749},
    .order = 8,
    .freq = 5644800u,
    .name = "mb_agg-dsd128"
};
static const ntf_filter_t ntf_mb_agg_dsd256 = {
    .a = {0.0003718463, 0.0045618576, 0.0302419867, 0.1109171648, 0.3708867477, 0.6372570382, 1.2845181658, 0.8889045039},
    .g = {0.0000050675, 0.0000415929, 0.0000955806, 0.0001388736},
    .order = 8,
    .freq = 11289600u,
    .name = "mb_agg-dsd256"
};
static const ntf_filter_t ntf_mb_agg_dsd512 = {
    .a = {0.0003718389, 0.0045609863, 0.0302476696, 0.1109181698, 0.3709666298, 0.6372874053, 1.2846387020, 0.8888927916},
    .g = {0.0000012669, 0.0000103982, 0.0000238953, 0.0000347187},
    .order = 8,
    .freq = 22579200u,
    .name = "mb_agg-dsd512"
};

/* mb_ultra: order=8, H_inf=4.0
 * Ultra aggressive order-8 (needs 8+ levels) */
static const ntf_filter_t ntf_mb_ultra_dsd64 = {
    .a = {0.0017712516, 0.0175138380, 0.0946253453, 0.2741882743, 0.7657107700, 1.0198036115, 1.7850163221, 0.9376404107},
    .g = {0.0000810795, 0.0006654515, 0.0015291072, 0.0022215911},
    .order = 8,
    .freq = 2822400u,
    .name = "mb_ultra-dsd64"
};
static const ntf_filter_t ntf_mb_ultra_dsd128 = {
    .a = {0.0017699776, 0.0174707162, 0.0947791096, 0.2741305950, 0.7673410453, 1.0202018471, 1.7868945793, 0.9375351303},
    .g = {0.0000202700, 0.0001663698, 0.0003823133, 0.0005554749},
    .order = 8,
    .freq = 5644800u,
    .name = "mb_ultra-dsd128"
};
static const ntf_filter_t ntf_mb_ultra_dsd256 = {
    .a = {0.0017696584, 0.0174599509, 0.0948175630, 0.2741162135, 0.7677488532, 1.0203014692, 1.7873642929, 0.9375087843},
    .g = {0.0000050675, 0.0000415929, 0.0000955806, 0.0001388736},
    .order = 8,
    .freq = 11289600u,
    .name = "mb_ultra-dsd256"
};
static const ntf_filter_t ntf_mb_ultra_dsd512 = {
    .a = {0.0017695786, 0.0174572605, 0.0948271772, 0.2741126206, 0.7678508202, 1.0203263786, 1.7874817306, 0.9375021963},
    .g = {0.0000012669, 0.0000103982, 0.0000238953, 0.0000347187},
    .order = 8,
    .freq = 22579200u,
    .name = "mb_ultra-dsd512"
};

/* mb_ext: order=10, H_inf=4.0
 * Extended order-10 (needs 8+ levels) */
static const ntf_filter_t ntf_mb_ext_dsd64 = {
    .a = {0.0000577193, 0.0008723661, 0.0070177750, 0.0325542191, 0.1332492138, 0.3157627445, 0.8270074099, 1.0385297937, 1.8026432924, 0.9376404101},
    .g = {0.0000000000, 0.0000810795, 0.0006654515, 0.0015291072, 0.0022215911},
    .order = 10,
    .freq = 2822400u,
    .name = "mb_ext-dsd64"
};
static const ntf_filter_t ntf_mb_ext_dsd128 = {
    .a = {0.0000574197, 0.0008683387, 0.0069972564, 0.0324605880, 0.1333168278, 0.3156118777, 0.8285295629, 1.0388956617, 1.8044893377, 0.9375351299},
    .g = {0.0000000000, 0.0000202700, 0.0001663698, 0.0003823133, 0.0005554749},
    .order = 10,
    .freq = 5644800u,
    .name = "mb_ext-dsd128"
};
static const ntf_filter_t ntf_mb_ext_dsd256 = {
    .a = {0.0000573450, 0.0008673344, 0.0069921357, 0.0324372176, 0.1333337692, 0.3155742248, 0.8289103610, 1.0389871987, 1.8049510051, 0.9375087837},
    .g = {0.0000000000, 0.0000050675, 0.0000415929, 0.0000955806, 0.0001388736},
    .order = 10,
    .freq = 11289600u,
    .name = "mb_ext-dsd256"
};
static const ntf_filter_t ntf_mb_ext_dsd512 = {
    .a = {0.0000573264, 0.0008670834, 0.0069908560, 0.0324313773, 0.1333380070, 0.3155648155, 0.8290055768, 1.0390100873, 1.8050664316, 0.9375021956},
    .g = {0.0000000000, 0.0000012669, 0.0000103982, 0.0000238953, 0.0000347187},
    .order = 10,
    .freq = 22579200u,
    .name = "mb_ext-dsd512"
};

/* mb_max: order=10, H_inf=6.0
 * Maximum order-10 (needs 16+ levels) */
static const ntf_filter_t ntf_mb_max_dsd64 = {
    .a = {0.0004905196, 0.0058359430, 0.0375978022, 0.1348015389, 0.4508321177, 0.8115308512, 1.7831217381, 1.6716620835, 2.5440800491, 0.9722846269},
    .g = {0.0000000000, 0.0000810795, 0.0006654515, 0.0015291072, 0.0022215911},
    .order = 10,
    .freq = 2822400u,
    .name = "mb_max-dsd64"
};
static const ntf_filter_t ntf_mb_max_dsd128 = {
    .a = {0.0004886502, 0.0058162059, 0.0375129345, 0.1345111378, 0.4508553747, 0.8111169077, 1.7850394386, 1.6719403508, 2.5459044561, 0.9722378366},
    .g = {0.0000000000, 0.0000202700, 0.0001663698, 0.0003823133, 0.0005554749},
    .order = 10,
    .freq = 5644800u,
    .name = "mb_max-dsd128"
};
static const ntf_filter_t ntf_mb_max_dsd256 = {
    .a = {0.0004881838, 0.0058112806, 0.0374917451, 0.1344386215, 0.4508612569, 0.8110135187, 1.7855191671, 1.6720099872, 2.5463606968, 0.9722261266},
    .g = {0.0000000000, 0.0000050675, 0.0000415929, 0.0000955806, 0.0001388736},
    .order = 10,
    .freq = 11289600u,
    .name = "mb_max-dsd256"
};
static const ntf_filter_t ntf_mb_max_dsd512 = {
    .a = {0.0004880672, 0.0058100498, 0.0374864495, 0.1344204976, 0.4508627317, 0.8109876773, 1.7856391185, 1.6720274012, 2.5464747646, 0.9722231990},
    .g = {0.0000000000, 0.0000012669, 0.0000103982, 0.0000238953, 0.0000347187},
    .order = 10,
    .freq = 22579200u,
    .name = "mb_max-dsd512"
};

/* Multibit NTF lookup by config name and DSD rate */
typedef struct {
    const char *config;
    int order;
    double h_inf;
    int min_levels;  /* minimum quantizer levels for stability */
    const ntf_filter_t *filters[4];  /* DSD64, DSD128, DSD256, DSD512 */
} ntf_multibit_config_t;

static const ntf_multibit_config_t ntf_multibit_configs[] = {
    {"mb_std", 6, 1.5, 2, {&ntf_mb_std_dsd64, &ntf_mb_std_dsd128, &ntf_mb_std_dsd256, &ntf_mb_std_dsd512}},
    {"mb_mod", 6, 2.5, 4, {&ntf_mb_mod_dsd64, &ntf_mb_mod_dsd128, &ntf_mb_mod_dsd256, &ntf_mb_mod_dsd512}},
    {"mb_agg", 8, 3.0, 8, {&ntf_mb_agg_dsd64, &ntf_mb_agg_dsd128, &ntf_mb_agg_dsd256, &ntf_mb_agg_dsd512}},
    {"mb_ultra", 8, 4.0, 8, {&ntf_mb_ultra_dsd64, &ntf_mb_ultra_dsd128, &ntf_mb_ultra_dsd256, &ntf_mb_ultra_dsd512}},
    {"mb_ext", 10, 4.0, 8, {&ntf_mb_ext_dsd64, &ntf_mb_ext_dsd128, &ntf_mb_ext_dsd256, &ntf_mb_ext_dsd512}},
    {"mb_max", 10, 6.0, 16, {&ntf_mb_max_dsd64, &ntf_mb_max_dsd128, &ntf_mb_max_dsd256, &ntf_mb_max_dsd512}},
    {NULL, 0, 0, 0, {NULL, NULL, NULL, NULL}}
};

#endif /* NTF_MULTIBIT_H */
