"""
Generate multibit-specific NTF coefficients for foo_dsd_trellis.
Outputs C arrays suitable for inclusion in ntf.c.

Usage: python tools/ntf_gen_multibit.py > include/ntf_multibit.h
"""
import deltasigma as ds
import numpy as np
import warnings
import sys
warnings.filterwarnings('ignore')

# DSD rates: multiplier × 44100
RATES = [
    ('DSD64',   64,  2822400),
    ('DSD128', 128,  5644800),
    ('DSD256', 256, 11289600),
    ('DSD512', 512, 22579200),
]

# Configurations to generate
CONFIGS = [
    # (name, order, H_inf, description)
    ('mb_std',   6, 1.5, 'Standard NTF (same as 1-bit, baseline multibit)'),
    ('mb_mod',   6, 2.5, 'Moderate aggressive (stable with 4+ levels)'),
    ('mb_agg',   8, 3.0, 'Aggressive order-8 (stable with 4+ levels)'),
    ('mb_ultra', 8, 4.0, 'Ultra aggressive order-8 (needs 8+ levels)'),
    ('mb_ext',  10, 4.0, 'Extended order-10 (needs 8+ levels)'),
    ('mb_max',  10, 6.0, 'Maximum order-10 (needs 16+ levels)'),
]

out = sys.stdout

out.write('/*\n')
out.write(' * foo_dsd_trellis - Multi-bit NTF coefficient tables\n')
out.write(' * Auto-generated by tools/ntf_gen_multibit.py using pydelsig\n')
out.write(' *\n')
out.write(' * CRFB form: a[] = feedforward, g[] = resonator\n')
out.write(' * Higher H_inf = more aggressive noise shaping (needs more quantizer levels)\n')
out.write(' */\n\n')
out.write('#ifndef NTF_MULTIBIT_H\n')
out.write('#define NTF_MULTIBIT_H\n\n')
out.write('#include "ntf.h"\n\n')

all_filters = []

for cfg_name, order, H_inf, desc in CONFIGS:
    out.write('/* %s: order=%d, H_inf=%.1f\n * %s */\n' % (cfg_name, order, H_inf, desc))

    for rate_name, osr, freq in RATES:
        try:
            H = ds.synthesizeNTF(order=order, osr=osr, opt=1, H_inf=H_inf)
            form = ds.realizeNTF(H, form='CRFB')
            a, g = form[0], form[1]

            var = 'ntf_%s_%s' % (cfg_name, rate_name.lower())
            a_str = ', '.join('%.10f' % x for x in a)
            g_str = ', '.join('%.10f' % x for x in g)
            n_g = len(g)

            out.write('static const ntf_filter_t %s = {\n' % var)
            out.write('    .a = {%s},\n' % a_str)
            out.write('    .g = {%s},\n' % g_str)
            out.write('    .order = %d,\n' % order)
            out.write('    .freq = %du,\n' % freq)
            out.write('    .name = "%s"\n' % ('%s-%s' % (cfg_name, rate_name.lower())))
            out.write('};\n')

            all_filters.append((cfg_name, rate_name, var, order, H_inf))

        except Exception as e:
            out.write('/* %s %s: synthesis FAILED (%s) */\n' % (cfg_name, rate_name, str(e)[:60]))

    out.write('\n')

# Generate lookup table
out.write('/* Multibit NTF lookup by config name and DSD rate */\n')
out.write('typedef struct {\n')
out.write('    const char *config;\n')
out.write('    int order;\n')
out.write('    double h_inf;\n')
out.write('    int min_levels;  /* minimum quantizer levels for stability */\n')
out.write('    const ntf_filter_t *filters[4];  /* DSD64, DSD128, DSD256, DSD512 */\n')
out.write('} ntf_multibit_config_t;\n\n')

out.write('static const ntf_multibit_config_t ntf_multibit_configs[] = {\n')
for cfg_name, order, H_inf, desc in CONFIGS:
    min_lev = 2 if H_inf <= 1.5 else (4 if H_inf <= 2.5 else (8 if H_inf <= 4.0 else 16))
    ptrs = []
    for rate_name, _, _ in RATES:
        var = 'ntf_%s_%s' % (cfg_name, rate_name.lower())
        found = any(v == var for _, _, v, _, _ in all_filters)
        ptrs.append('&%s' % var if found else 'NULL')
    out.write('    {"%s", %d, %.1f, %d, {%s}},\n' % (
        cfg_name, order, H_inf, min_lev, ', '.join(ptrs)))
out.write('    {NULL, 0, 0, 0, {NULL, NULL, NULL, NULL}}\n')
out.write('};\n\n')

out.write('#endif /* NTF_MULTIBIT_H */\n')

# Print summary to stderr
sys.stderr.write('\nGenerated %d NTF filters across %d configs\n' % (
    len(all_filters), len(CONFIGS)))
for cfg_name, order, H_inf, desc in CONFIGS:
    n = sum(1 for c, _, _, _, _ in all_filters if c == cfg_name)
    sys.stderr.write('  %s (o=%d H=%.1f): %d rates\n' % (cfg_name, order, H_inf, n))
