/*
 * foo_dsd_trellis — Build version info
 *
 * BUILD_GIT_HASH is generated by the pre-build event into
 * build_version_hash.h. If that file doesn't exist, the
 * fallback "unknown" is used.
 */
#ifndef BUILD_VERSION_H
#define BUILD_VERSION_H

#if __has_include("build_version_hash.h")
#include "build_version_hash.h"
#endif

#ifndef BUILD_GIT_HASH
#define BUILD_GIT_HASH "unknown"
#endif

#define BUILD_VERSION  "1.0.2"
#define BUILD_DATE     __DATE__
#define BUILD_TIME     __TIME__

#endif /* BUILD_VERSION_H */
